# -*- coding: utf-8 -*-
"""Week3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l9qr-mdHJY4HszdPM71L5UoFH6fW3pVG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Metro_Interstate_Traffic_Volume.csv")
df.head()

#no. of rows and columns
df.shape

df.columns

df.info()

#summary statistics
df.describe()

"""Finding missing values"""

df.isnull().sum()

#percentage missing
(df.isnull().sum()/len(df))*100

"""Duplicate rows: It is important to remove duplicate rows so that the average doesn't become biased"""

df.drop_duplicates(inplace=True)
df.duplicated().sum()

"""Trafic vokume distribution plot"""

plt.figure(figsize=(8,5))
sns.histplot(df["traffic_volume"],bins=40)
plt.title("Trafic Volume distribution plot")
plt.show()

"""Correlation heatmap:"""

plt.figure(figsize=(8,5))
sns.heatmap(df.select_dtypes(include=np.number).corr(),annot=True,cmap="coolwarm")
plt.show()

"""Boxplot:
To find any extreme points in the dataset. It shows us the numerical features of the dataset
"""

plt.figure(figsize=(8,5))
sns.boxplot(x=df["traffic_volume"])
plt.show()

"""Handling missing values"""

df["holiday"]=df["holiday"].fillna("None")
#checking again
df.isnull().sum()

"""Feature Engineering: Creating better features from data to make it more relevant so that the model can learn better. For example, 2012-10-02 09:00:00 this is just a random text for the computer, random forest does not know how to interpret it. But we know that Tuesday 9 am does affect the traffic volume compared to Sunday 6 pm"""

df["date_time"]=pd.to_datetime(df["date_time"])
#extract
df["hour"]=df["date_time"].dt.hour
df["month"]=df["date_time"].dt.month
df["day"]=df["date_time"].dt.day
df["weekday"]=df["date_time"].dt.weekday
df["is_weekend"]=(df["weekday"]>=5).astype(int)
#dropping original name
df.drop("date_time",axis=1,inplace=True)

"""importing sklearn,models and metrics"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor
from xgboost import XGBRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

"""Encoding and Train test split"""

x=df.drop("traffic_volume",axis=1)
y=df["traffic_volume"]

#categorical columns
cat_cols=["holiday","weather_main","weather_description"]
#numerical columns
num_cols=x.select_dtypes(include=np.number).columns

#one hot encoder puts numerical values to string ones
preprocessor = ColumnTransformer(
    transformers=[
        ("cat",
         OneHotEncoder(handle_unknown="ignore"),
         cat_cols),

        ("num",
         "passthrough",
         num_cols)
    ]
)

x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

"""RANDOM FOREST"""

rf=Pipeline([("preprocessor",preprocessor),
 ("model",RandomForestRegressor(n_estimators=50,n_jobs=1,random_state=42))])
rf.fit(x_train,y_train)
rf_pred=rf.predict(x_test)

rf_mae = mean_absolute_error(y_test, rf_pred)
rf_mse = mean_squared_error(y_test, rf_pred)
rf_rmse = np.sqrt(rf_mse)
rf_r2 = r2_score(y_test, rf_pred)
print("Random Forest: ")
print("MAE :", rf_mae)
print("RMSE :", rf_rmse)
print("R2 :", rf_r2)

"""
ADABOOST



"""

ada=Pipeline([("preprocessor",preprocessor),
("model",AdaBoostRegressor(n_estimators=50,random_state=42))])
ada.fit(x_train,y_train)
ada_pred=ada.predict(x_test)

ada_mae=mean_absolute_error(y_test,ada_pred)
ada_mse=mean_squared_error(y_test,ada_pred)
ada_rmse=np.sqrt(ada_mse)
ada_r2=r2_score(y_test,ada_pred)
print("AdaBoost: ")
print("MAE :", ada_mae)
print("RMSE :", ada_rmse)
print("R2 :", ada_r2)

"""XGBoost"""

xgb=Pipeline([("preprocessor",preprocessor),
              ("model",XGBRegressor(n_estimators=50,
                                    max_depth=6,
                                    learning_rate=0.1,
                                    random_state=42))])
xgb.fit(x_train,y_train)
xgb_pred=xgb.predict(x_test)

xgb_mae = mean_absolute_error(y_test, xgb_pred)
xgb_mse = mean_squared_error(y_test, xgb_pred)
xgb_rmse = np.sqrt(xgb_mse)
xgb_r2 = r2_score(y_test, xgb_pred)
print("XGBoost")
print("MAE :", xgb_mae)
print("RMSE :", xgb_rmse)
print("R2 :", xgb_r2)

"""COMPARISON TABLE"""

comparison = pd.DataFrame({
    "Model": [
        "Random Forest",
        "AdaBoost",
        "XGBoost"
    ],
    "MAE": [
        rf_mae,
        ada_mae,
        xgb_mae
    ],
    "RMSE": [
        rf_rmse,
        ada_rmse,
        xgb_rmse
    ],
    "R2 Score": [
        rf_r2,
        ada_r2,
        xgb_r2
    ]})
comparison

"""HENCE RANDOM FOREST IS THE BEST ONE CAUSE Mean Absolute Error and Root Mean Square Errors are the lowest and R2 score is the highest

COMPARISON GRAPH:
"""

comparison.set_index("Model").plot(
    kind="bar",
    figsize=(10,5))
plt.title("Comparison of Ensemble Models")
plt.grid(True)
plt.show()

"""Actual vs predicted (Best Model)"""

plt.figure(figsize=(7,7))
plt.scatter(y_test,
            rf_pred,
            alpha=0.4)
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Actual vs Predicted (Random Forest)")
plt.show()